# Macro file: run.mac

# HandsOn 3-1 #1
# Write the verbose for run as level 1.


# HandsOn 3-1 #2, 3
# Write the verbose for tracking.


# HandsOn 2-4 #9
# Make a point type gamma source.
# HandsOn 2-4 #10
# Make a line type gamma source.
# HandsOn 2-4 #11
# Make a plane type gamma source.
# HandsOn 2-4 #12
# Make a isotropic point type gamma source.


# HandsOn 2-4 #13
# Change the number of primaries.
/run/beamOn 100
