/vis/open OGL 600x600

/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/viewer/set/viewpointVector 0.64 0.64 0.45
/vis/viewer/zoomTo 1

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

/vis/viewer/set/style surface
/vis/geometry/set/visibility World 0 false

/vis/viewer/set/autoRefresh true
/vis/verbose warning
